ETCD_NAME={{ inventory_hostname }}
ETCD_INITIAL_CLUSTER="{{ INITIAL_CLUSTER }}"
ETCD_INITIAL_CLUSTER_TOKEN="devops_token"
ETCD_INITIAL_CLUSTER_STATE="new"
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://{{ local_address }}:2380"
ETCD_DATA_DIR="/var/lib/etcd/postgresql"
ETCD_LISTEN_PEER_URLS="http://{{ local_address }}:2380"
ETCD_LISTEN_CLIENT_URLS="http://{{ local_address }}:2379,http://localhost:2379"
ETCD_ADVERTISE_CLIENT_URLS="http://{{ local_address }}:2379"