server {
    listen       80;
    server_name  _;

    #access_log  /var/log/angie/host.access.log  main;

    root   /mnt/gfs2_storage/wordpress;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    location ~ \.php$ {
   #     root           html;
        #fastcgi_pass   127.0.0.1:9000;
        #fastcgi_intercept_errors on;
        #fastcgi_param PHP_VALUE "display_errors=On \n error_reporting=E_ALL";
        fastcgi_pass   unix:/run/php/php8.3-fpm.sock;
        fastcgi_index  index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }
	
	# Cache static files
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|webp)$ {
       expires max;
       log_not_found off;
    }

    # Deny access to hidden files and sensitive WP files
    
    location ~ /\. { 
        deny all; 
        }
    
    location = /favicon.ico { 
        log_not_found off; 
        access_log off; 
        }
    location = /robots.txt { 
        log_not_found off; 
        access_log off; 
        allow all; 
        }

    # Security: Deny PHP execution in uploads directory
   location ~* /(?:uploads|files)/.*\.php$ {
       deny all;
   }

    # deny access to .htaccess files, if Apache's document root
    # concurs with angie's one
    #
    location ~ /\.ht {
       deny  all;
    }
}